### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by proydakov** [nezticle/RaspberryPi-BuildRoot#13]
Assemble on the wiki. An error has occurred.

a - ../obj_g/key_defined.o
a - ../obj_g/keybound.o
a - ../obj_g/keyok.o
a - ../obj_g/version.o
ranlib ../lib/libncurses_g.a
/home/evgeny/bsquask_sdk/host/usr/bin/ccache /usr/bin/gcc ../objects/tic.o ../objects/dump_entry.o -L/home/evgeny/bsquask_sdk/host/lib -L/home/evgeny/bsquask_sdk/host/usr/lib -Wl,-rpath,/home/evgeny/bsquask_sdk/host/usr/lib -I../progs -I. -DHAVE_CONFIG_H -I. -I../include  -D_GNU_SOURCE -DNDEBUG -I/home/evgeny/bsquask_sdk/host/usr/include/ncurses -O2 -I/home/evgeny/bsquask_sdk/host/include -I/home/evgeny/bsquask_sdk/host/usr/include  --param max-inline-insns-single=1200 -static -L../lib -lncurses -L../lib -lncurses -dynamic   -o tic
/usr/lib64/gcc/x86_64-suse-linux/4.7/../../../../x86_64-suse-linux/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[2]: **\* [tic] Error 1
make[1]: **\* [/home/evgeny/bsquask_sdk/build/host-ncurses-5.7/.stamp_built] Error 2
make: **\* [all] Error 2

How to solve it?

**Comment by nezticle** [comment]
It looks like your build is failing trying to build the host (x86_64) version of libncurses (static).  Since this is a static build your host system (SUSE x86_64) needs to have the glibc static library files.  I've not actually tested building with SUSE before so I'm not sure of the correct package you need, but this is a problem with the host toolchain, and not with the cross compilation toolchain provided.  I hope this extra info helps.

**Comment by proydakov** [comment]
After installing the glibc-devel-static error is gone. Thank you.
