### ISSUE TITLE
undefined reference to `memcpy@GLIBC_2.14'

### ISSUE THREAD

**Issue by peterwillcn** [nezticle/RaspberryPi-BuildRoot#32]
gvarianttype.c:487: warning: 'g_variant_type_check' defined but not used
echo glib-unix.h glib-object.h glib.h galloca.h garray.h gasyncqueue.h gatomic.h gbacktrace.h gbase64.h gbitlock.h gbookmarkfile.h gcache.h gchecksum.h gcompletion.h gconvert.h gdataset.h gdate.h gdatetime.h gdir.h gerror.h gfileutils.h ghash.h ghmac.h ghook.h ghostutils.h gi18n.h gi18n-lib.h giochannel.h gkeyfile.h glist.h gmacros.h gmain.h gmappedfile.h gmarkup.h gmem.h gmessages.h gnode.h goption.h gpattern.h gpoll.h gprimes.h gqsort.h gquark.h gqueue.h grand.h gregex.h grel.h gscanner.h gsequence.h gshell.h gslice.h gslist.h gspawn.h gstdio.h gstrfuncs.h gtestutils.h gstring.h gthread.h gthreadpool.h gtimer.h gtimezone.h gtree.h gtypes.h gunicode.h gurifuncs.h gutils.h gvarianttype.h gvariant.h gwin32.h gprintf.h > glib-public-headers.txt.tmp && mv glib-public-headers.txt.tmp glib-public-headers.txt
  CCLD   libglib-2.0.la
  CCLD   gtester
/opt/glibc-2.14/lib/libpthread.so.0: undefined reference to `memcpy@GLIBC_2.14'

**Comment by peterwillcn** [comment]
redhat 6.3 and centos6.3   >  strings /lib64/libc.so.6 |grep GLIBC_  can RaspberryPi-BuildRoot use GLIBC_2.12 
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_PRIVATE

**Comment by nezticle** [comment]
This is likely because I've generated the Bsquask toolchains on Ubuntu 12.04 systems.  I don't plan re-generate the toolchains using an older system, but it is possible to use a different toolchain than the one I provide (via "make xconfig", or "make menu-config")

It's also possible to re-generate the cross-compilation toolchain yourself using my configuration with crosstool-ng.  To retreive the configuration I used, you just need to run the following command in $BSQUASK_DIR/host/usr/bin/:
arm-raspberrypi-linux-gnueabi-ct-ng-config
