### ISSUE TITLE
-opengl es2 missing in Qt ./configure in Walkthrough?

### ISSUE THREAD

**Issue by arturormk** [nezticle/RaspberryPi-BuildRoot#4]
I had to add this option when calling ./configure to build qtbase. Without it the link stage would fail trying to link libGL.

It might have something to do with the fact that I got the Qt5 source code the “normal” way, through:

git clone git://gitorious.org/qt/qt5.git qt5
cd qt5
perl init-repository
cd qtbase

**Comment by nezticle** [comment]
Thank you for the feedback.  I've not tried to build qt using the qt5 project (instead of just one module at a time) for bsquask yet.  I'm surprised that you manually needed to specify the -opengl es2, since -device pi should make sure that this will be set through passing config.tests.  I'm in the process of updating and retesting the instructions now, so I will check this out as well.

**Comment by nezticle** [comment]
I've now included packages for qtbase, qtxmlpatterns, qtjsbackend, qtdeclarative and qtmultimedia (and wayland/qtwayland soon) in the default configuration.  OpenGLES 2.0 support is detected automatically when using -device pi (as long as VideoCore package is built first).
